
post http://localhost:3500/user/register
Content-Type: application/json

{
    "userName":"James Kariuki",
    "email":"jameskariuki@gmail.com",
    "phone_no":"0708090809",
     "password":"James!123"
     
    
}


###
#login user
POST http://localhost:3500/user/login
Content-Type: application/json

{
    "email":"jameskariuki@gmail.com",
    "password":"James!123"

}


###
#get all user

get http://localhost:4600/user/
token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJDM0M5RUZCMC0wQ0FCLTQ4NTYtOUQ5QS1BODE5NkE2MDVBQUQiLCJ1c2VyTmFtZSI6Ikpvc2h1YSIsImVtYWlsIjoiam9zaHVhLm9jaGllbmdAdGhlaml0dS5jb20iLCJBc3NpZ25lZFByb2plY3RJRCI6bnVsbCwicm9sZSI6ImVtcGxveWVlIiwiV2VsY29tZWQiOmZhbHNlLCJpc0Fzc2lnbmVkIjpmYWxzZSwiaWF0IjoxNjk5NDQ3MzU1LCJleHAiOjE2OTk0NTA5NTV9.BhaZjKQghSAfaFg5K0J0skrK5JgjGGr87rCaRVe6Dg0


###
#check user details
GET http://localhost:3500/user/check_user_details
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiIwNTg5OTkzNS0wNTgzLTQyM2EtOTVmMy01NzNhZTYyOGRjMjUiLCJ1c2VyTmFtZSI6IkphbWVzIEthcml1a2kiLCJlbWFpbCI6ImphbWVza2FyaXVraUBnbWFpbC5jb20iLCJBc3NpZ25lZFByb2plY3RJRCI6bnVsbCwicm9sZSI6ImVtcGxveWVlIiwiV2VsY29tZWQiOmZhbHNlLCJpc0Fzc2lnbmVkIjpmYWxzZSwiaWF0IjoxNzAwNDcxMjMzLCJleHAiOjE3MDA0NzQ4MzN9.h5ee7HD_vKjqM4lQTh_uoENexbOAuv28E0ZFL-HH9-w



###
#admin assign project

POST http://localhost:4600/project/assignProject
Content-Type: application/json

{
   
    "projectName": "BackgroundSerices",
    "projectDescription": "build company chatbot",
    "endDate": "2023-11-9",
    "AssignedUserEmail": "joshua.ochieng@thejitu.com",  
    "AssignedUserName": "Joshua Ochieng"  
}

###
#delete project
DELETE  http://localhost:4600/project/deleteProject
Content-Type: application/json

{
   
    "projectID":"c976d311-9c7d-4c65-9279-4915decdad33"
   
}


###
#get all projects
get  http://localhost:4600/project/

###
#get single project
get  http://localhost:4600/project/singleProject
Content-Type: application/json

{
   
    "AssignedUserEmail":"joshua.ochieng@thejitu.com"
   
}

###
#update completed project
post http://localhost:4600/project/updateProject
Content-Type: application/json

{
   
    "projectID":"1da4856b-edde-47f2-90d4-603913e26b7f"
   
}

###
#fetch All Users

get http://localhost:4600/project/getUsers


###
#user updates status

post http://localhost:4600/project/updateStatus
Content-Type: application/json

{
   
    "AssignedUserEmail":"joshua.ochieng@thejitu.com",
    "NewStatus":"completed"
   
}

###
#get project status
get http://localhost:4600/project/getStatus
Content-Type: application/json

{
   
    "AssignedUserEmail":"joshua.ochieng@thejitu.com"
   
}

###
#login user
get http://localhost:3500/user/singleUser
Content-Type: application/json

{
    "email":"savageochieng@gmail.com"
    


}